model:
  end_time: '2022-05-15 00:00:00'
  start_time: '2022-05-14 00:00:00'
  time_step: '30s'
  root_path: 'temp'
processes:
- riverine:
    configuration_path: riverine_config.yml
    time_step: '30s'
- temperature:
    wind_a: 1.3
    wind_b: 1.5
    wind_c: 3.0
