name: clearwater_dev_env
channels:
  - conda-forge
  - nodefaults # Speeds solving env, by limiting the number of options

dependencies:
  # main package dependencies
  - python >= 3.11
  - scipy # installs numpy, pandas and most pyData libraries
  - numba
  - xarray
  - pooch # for xarray tutorial dataset

  # for testing and static analysis
  - pytest
  - pytest-cov
  - pyright

  # for performance testing
  - snakeviz

  # Visualization
  - hvplot  # hvPlot installs most HoloViz libs, https://holoviz.org
  # Interactivity via Jupyter Notebooks
  - jupyterlab
  - nodejs  # required for many extensions
  - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
  - ipywidgets  # Required for HoloViz interactivity

  # Dev tools: Language Server Protocol (LSP) (Optional), for...
    # code navigation + hover suggestions + linters + autocompletion + rename
  - python-lsp-server >=1.6 # LSP extension for Python (pylsp), including:
    # Rope for Completions and renaming
    # Pyflakes linter to detect various errors
    # McCabe linter for complexity checking
    # pycodestyle linter for style checking
    # pydocstyle linter for docstring style checking (disabled by default)
    # autopep8 for code formatting
    # YAPF for code formatting (preferred over autopep8)
    # flake8 for error checking (disabled by default)
    # pylint for code linting (disabled by default)
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - jupyterlab-lsp # Provides both server extension and lab extension

  # environment and package management
  - conda
  - conda-build
  - conda-libmamba-solver  # Faster env solver, https://conda.github.io/conda-libmamba-solver/
  - mamba
  # PIP install requirements only if it is not  possible with conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
  - pip
