[project]
authors = [{name = "Paul Tomasula", email = "ptomasula@gmail.com"}]
name = "ClearWater-modules"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies=[
    "dask",
    "jupyterlab",
    "numpy",
    "pyyaml",
    "xarray",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64","linux-64"]

#[tool.pixi.pypi-dependencies]
#ClearWater-modules = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.feature.dev.pypi-dependencies]
pytest = "*"
clearwater_modules = { path = ".", editable = true}
clearwater_data = { path = "../clearwater-data", editable = true}
clearwater_riverine = {path = "../clearwater-riverine", editable=true}

[tool.pixi.tasks]
verify-install = {cmd = "python -c \"import clearwater_data; import clearwater_riverine; import clearwater_modules;\""}

[tool.pixi.dependencies]
pytest = ">=9.0.2,<10"
pytest-cov = ">=7.0.0,<8"

[tool.pytest.ini_options]
addopts = """
    --cov=clearwater_modules_v2
    --cov-report=term-missing
    --cov-report=html
"""
testpaths = ["tests"]
