#!/bin/sh

cat clearwater_modules_v3_nsm1_audit_summary.md clearwater_modules_v3_nsm1_audit_algae.md clearwater_modules_v3_nsm1_audit_c_dox.md clearwater_modules_v3_nsm1_audit_n_p.md clearwater_modules_v3_nsm1_audit_simple_constituents.md clearwater_modules_v3_nsm1_audit_utilities_params.md > combined.md

