# The `model` section defines the model configuration parameters.
model:
  # The start datetime for the model simulation. It sould be specified as string and 
  #match the pandas.to_datetime formatting requirements
  # https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas.to_datetime
  start_time: '2022-05-14 00:00:00'
  # The end datetime for the model simulation. It sould be specified as string and 
  #match the pandas.to_datetime formatting requirements
  # https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas.to_datetime
  end_time: '2022-05-15 00:00:00'
  #This is the main time step for the model. It should be specified as a string and 
  #match the pandas.Timedelta formatting requirements
  # https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html
  time_step: '30s'
  #This is the root directory for the model to create input, output and tempory files
  root_path: 'temp'
  #This is a list of variable names (as string) to output to the model's output file
  output_variables: ["air_temperature", "solar_radiation"]

# The `processes` section defines the processes to be run in the model.
# Here you will configure each process you would like executed in the model. 
# This block is specified as a list of process names and their configuration information.
# Though this is a list, the order of the processes does not matter or impact the model's 
# order of operations. 

processes: #this is the top level block specification

# Riverine instance, will be a instance of the transport modules contained in Riverine
- riverine:
    # Required parameter
    configuration_path: riverine_config.yml
    # Optional parameter
    time_step: '30s' #optional process specific timestep. This cannot be less than the model_step.

# Temperature instance, will be a instance of the temperature simulation in modules.
# This process performs an energy balance on the water column to update the water temperature.
# This is formerly the (TSM) module of version 1.
- temperature:
    # REQUIRED PARAMETERS
    # TODO: We should get Billy to both explain and provide guidance on wind parameters
    wind_a: 1.3 #Wind function parameter
    wind_b: 1.5 #Wind function parameter
    wind_c: 3.0 #Wind function parameter
    # Optional parameters
    time_step: '60s' #optional process specific timestep. This cannot be less than the model_step.

#The `data_sources` section defines the input data.
#Here you will provide a name for each data source, 
#and then configure information for the provider
data_sources:
  #base source configuration
  #`name:` This is name for the data source and will used later to match sources to their variables
  #`provider:` This is the type of data source provider (csv, float, zarr, etc.). 
  #`data:` This is the provider configuration block. Information here is provider specific. 
  
  #example_csv:
  example_csv_source:
    provider: csv 
    #
    data:
      #REQUIRED PARAMETERS
      file_path: absolute_path/to/file.csv #Note relative path not yet tested
      #OPTIONAL PARAMETERS
      time_field: time #Default 'Datetime'. This is the string name of the time_field for the CSV file. 
    
    #example_float:
    example_float_source:
      provider: float
      data:
        #REQUIRED PARAMETER
        value: 1.0 #Floating point value

# The `variable_map` section crosswalks the various data sources to the variables in the model.
# The mapping uses a key:value pair, where: 
# - the key is the variable name in the model.
# - the value is the data source name and field name, separated by a pipe (|).
# Notes: the order in which you specify the variables in the mapping does not matter.

variable_map:

  # for float sources you only need to provide the source name
  wind_speed: example_float_source

  # for CSV sources you should provide the field name in addition to the source name
  air_temperature: example_csv_source|air_temperature
  solar_radiation: example_csv_source|Solar
